// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace 南岩ERP.TableTest;

public partial class nanotableContext : DbContext
{
    public nanotableContext(DbContextOptions<nanotableContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Table_1> Table_1 { get; set; }

    public virtual DbSet<Table_2> Table_2 { get; set; }

    public virtual DbSet<Table_3> Table_3 { get; set; }

    public virtual DbSet<Table_4> Table_4 { get; set; }

    public virtual DbSet<Table_5> Table_5 { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Table_1>(entity =>
        {
            entity.Property(e => e.name)
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.name1)
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.name2)
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.name3)
                .HasMaxLength(10)
                .IsFixedLength();
            entity.Property(e => e.name4)
                .HasMaxLength(10)
                .IsFixedLength();
        });

        modelBuilder.Entity<Table_2>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Table_2__3213E83F55B475F9");

            entity.Property(e => e.name1)
                .HasMaxLength(50)
                .IsFixedLength();
            entity.Property(e => e.name2)
                .HasMaxLength(50)
                .IsFixedLength();
            entity.Property(e => e.name3)
                .HasMaxLength(50)
                .IsFixedLength();
            entity.Property(e => e.name4)
                .HasMaxLength(50)
                .IsFixedLength();
            entity.Property(e => e.name5)
                .HasMaxLength(50)
                .IsFixedLength();
            entity.Property(e => e.name6)
                .HasMaxLength(50)
                .IsFixedLength();
        });

        modelBuilder.Entity<Table_3>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Table_3__3213E83F1F981307");

            entity.Property(e => e.name1)
                .HasMaxLength(50)
                .IsFixedLength();
            entity.Property(e => e.name2)
                .HasMaxLength(50)
                .IsFixedLength();
            entity.Property(e => e.name3)
                .HasMaxLength(50)
                .IsFixedLength();
            entity.Property(e => e.name4)
                .HasMaxLength(50)
                .IsFixedLength();
            entity.Property(e => e.name5)
                .HasMaxLength(50)
                .IsFixedLength();
            entity.Property(e => e.name6)
                .HasMaxLength(50)
                .IsFixedLength();
        });

        modelBuilder.Entity<Table_4>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Table_4__3213E83F6299EBDF");

            entity.Property(e => e.name1)
                .HasMaxLength(50)
                .IsFixedLength();
            entity.Property(e => e.name2)
                .HasMaxLength(50)
                .IsFixedLength();
            entity.Property(e => e.name3)
                .HasMaxLength(50)
                .IsFixedLength();
            entity.Property(e => e.name4)
                .HasMaxLength(50)
                .IsFixedLength();
            entity.Property(e => e.name5)
                .HasMaxLength(50)
                .IsFixedLength();
            entity.Property(e => e.name6)
                .HasMaxLength(50)
                .IsFixedLength();
        });

        modelBuilder.Entity<Table_5>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__Table_5__3213E83F1CAE2775");

            entity.Property(e => e.name1)
                .HasMaxLength(50)
                .IsFixedLength();
            entity.Property(e => e.name2)
                .HasMaxLength(50)
                .IsFixedLength();
            entity.Property(e => e.name3)
                .HasMaxLength(50)
                .IsFixedLength();
            entity.Property(e => e.name4)
                .HasMaxLength(50)
                .IsFixedLength();
            entity.Property(e => e.name5)
                .HasMaxLength(50)
                .IsFixedLength();
            entity.Property(e => e.name6)
                .HasMaxLength(50)
                .IsFixedLength();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}