// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace 南岩ERP.TableTest;

public partial class Table_1
{
    public int id { get; set; }
    public string name { get; set; }

    public string name1 { get; set; }

    public string name2 { get; set; }

    public string name3 { get; set; }

    public string name4 { get; set; }
}
