// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace 南岩ERP.TableTest;

public partial class Table_5
{
    public int id { get; set; }

    public string name1 { get; set; }

    public string name2 { get; set; }

    public string name3 { get; set; }

    public string name4 { get; set; }

    public string name5 { get; set; }

    public string name6 { get; set; }
}