// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERP.教育訓練EFModels;

public partial class 員工表
{
    public string 員工編號 { get; set; }

    public string 姓名 { get; set; }

    public DateTime 報到日期 { get; set; }

    public string 性別 { get; set; }

    public int? 部門編號 { get; set; }

    public string 職稱 { get; set; }
}