// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERP.教育訓練EFModels;

public partial class 員工職務表
{
    public int Id { get; set; }

    public string 員工編號 { get; set; }

    public string 職務 { get; set; }
}