// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace 南岩ERP.教育訓練EFModels;

public partial class 教育訓練檔案
{
    public int 檔案流水號 { get; set; }

    public string 檔案名稱 { get; set; }
}