// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ERP.教育訓練EFModels;

public partial class 申請表
{
    public int 申請表流水號 { get; set; }

    public string 申請表編號 { get; set; }

    public string 申請人 { get; set; }

    public string 申請部門 { get; set; }
    [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
    public DateTime 申請日期 { get; set; }

    public string 訓練方式 { get; set; }

    public string 聯絡單位 { get; set; }

    public string 訓練費用 { get; set; }

    public string 課程名稱 { get; set; }

    public string 訓練目的 { get; set; }
    [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
    public DateTime 訓練日期 { get; set; }

    public string 時間 { get; set; }

    public int? 時數 { get; set; }

    public string 主辦單位 { get; set; }

    public string 上課地點 { get; set; }

    public string 上課人員 { get; set; }

    public string 講師 { get; set; }

    public bool 報名表 { get; set; }

    public bool 宣傳單 { get; set; }

    public bool 其它 { get; set; }

    public bool 簽到表 { get; set; }

    public bool 測驗問卷 { get; set; }

    public bool 結業證書 { get; set; }

    public bool 心得報告 { get; set; }

    public bool 學員滿意度調查表 { get; set; }

    public bool 實作 { get; set; }

    public string 訓練管理單位協助事項 { get; set; }

    public string 備註 { get; set; }

    public DateTime? 建檔日期 { get; set; }

    public DateTime? KEYIN_DATE { get; set; }

    public string MAN_ID { get; set; }

    public string HOST_NAME { get; set; }

    public string HOST_IP { get; set; }
}