// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace 南岩ERP.教育訓練EFModels;

public partial class 職務文件關聯表
{
    public int Id { get; set; }

    public int? 部門編號 { get; set; }

    public string 職務 { get; set; }

    public string 文件編號 { get; set; }
}