// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace 南岩ERP.教育訓練EFModels;

public partial class 職務表
{
    public int? 部門編號 { get; set; }

    public string 職務 { get; set; }

    public string 職別 { get; set; }

    public string 職級 { get; set; }

    public string 訓練方式 { get; set; }

    public byte? 筆試 { get; set; }

    public byte? 口試 { get; set; }

    public byte? 實作 { get; set; }

    public string 其它 { get; set; }
}