// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace 南岩ERP.教育訓練EFModels;

public partial class 部門表
{
    public int 部門編號 { get; set; }

    public string 部門名稱 { get; set; }
}