// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace 南岩ERP.MisEFModels;

public partial class 機器設備硬碟備份紀錄
{
    public int 流水號 { get; set; }

    public string 設備名稱 { get; set; }
    [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
    [ConcurrencyCheck]
    public DateTime 備份日期 { get; set; }
    [ConcurrencyCheck]
    public bool Ghost { get; set; }
    [ConcurrencyCheck]
    public bool TrueImage { get; set; }
    [ConcurrencyCheck]
    public string 備註 { get; set; }
    public bool IsConcurrencyToken { get; }
    public DateTime? 建檔日期 { get; set; }

    public DateTime? KEYIN_DATE { get; set; }

    public string HOST_IP { get; set; }

    public string MAN_ID { get; set; }

    public string HOST_NAME { get; set; }
}