// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace 南岩ERP.MisEFModels;

public partial class 資訊設備明細表
{
    public int 流水號 { get; set; }

    public string 公司 { get; set; }

    public string 使用部門 { get; set; }

    public string 使用者_or_設備名稱_員工編號_姓名_分機 { get; set; }

    public string 放置位置 { get; set; }

    public string 電腦名稱_or_設備型號 { get; set; }

    public string 設備序號 { get; set; }

    public string IP_Address { get; set; }

    public string MAC_ADDrEss { get; set; }

    public string 原始作業系統_免費升級系統 { get; set; }

    public string 主機版 { get; set; }

    public string CPU { get; set; }

    public string 記億體_插槽_速度_最大 { get; set; }

    public string RAM { get; set; }

    public string 硬碟容量 { get; set; }

    public string PCI_E_4_0_x16 { get; set; }

    public string PCI_E_3_0_x16 { get; set; }

    public string PCI_E_3_0_x1 { get; set; }

    public string PCI_E_2_0_x16 { get; set; }

    public string PCI_E_x4 { get; set; }

    public string PCI_E_x1 { get; set; }

    public string PCI { get; set; }

    public string AGP { get; set; }

    public string ISA { get; set; }

    public bool 上網 { get; set; }

    public string 網卡1 { get; set; }

    public string 網卡2 { get; set; }

    public string 網卡3 { get; set; }

    public string 網路接線盒號碼 { get; set; }

    public string 電話接線盒號碼 { get; set; }

    public string Office版本 { get; set; }

    public string 郵件軟體 { get; set; }

    public string Mail_Address { get; set; }

    public string Win10_Microsoft帳戶 { get; set; }

    public string Win10_Microsoft帳戶密碼 { get; set; }

    public string 備註 { get; set; }

    public string F31 { get; set; }

    public DateTime? 建檔日期 { get; set; }

    public DateTime? KEYIN_DATE { get; set; }

    public string HOST_IP { get; set; }

    public string MAN_ID { get; set; }

    public string HOST_NAME { get; set; }
}