// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERP.MisEFModels;

public partial class 軟體版權明細
{
    public int 流水號 { get; set; }

    public string 公司 { get; set; }

    public string 軟體名稱 { get; set; }

    public int? 數量 { get; set; }

    public string 安裝電腦名稱 { get; set; }

    public string MAC { get; set; }

    public string 產品序號 { get; set; }

    public string 備註 { get; set; }

    public string 帳號 { get; set; }

    public string 密碼 { get; set; }

    public int? 已使用 { get; set; }

    public int? 主機板故障報廢 { get; set; }

    public int? 未使用 { get; set; }

    public DateTime? 建檔日期 { get; set; }

    public DateTime? KEYIN_DATE { get; set; }

    public string HOST_IP { get; set; }

    public string MAN_ID { get; set; }

    public string HOST_NAME { get; set; }
}