// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using ERP.TESTModels.TESTEFModels;

namespace ERP.TESTModels.TESTEFModels
{
    public partial class TESTContext
    {

        [DbFunction("WIP_001_生產回報_Cassette_No", "dbo")]
        public IQueryable<WIP_001_生產回報_Cassette_NoResult> WIP_001_生產回報_Cassette_No(string 工單編號)
        {
            return FromExpression(() => WIP_001_生產回報_Cassette_No(工單編號));
        }

        [DbFunction("WIP_001_流程卡資料_各站異常代號", "dbo")]
        public IQueryable<WIP_001_流程卡資料_各站異常代號Result> WIP_001_流程卡資料_各站異常代號(string 站別編號)
        {
            return FromExpression(() => WIP_001_流程卡資料_各站異常代號(站別編號));
        }

        [DbFunction("WIP_001_流程卡資料_機台編號", "dbo")]
        public IQueryable<WIP_001_流程卡資料_機台編號Result> WIP_001_流程卡資料_機台編號(string 工單編號, string 生產站別)
        {
            return FromExpression(() => WIP_001_流程卡資料_機台編號(工單編號, 生產站別));
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<WIP_001_生產回報_Cassette_NoResult>().HasNoKey();
            modelBuilder.Entity<WIP_001_流程卡資料_各站異常代號Result>().HasNoKey();
            modelBuilder.Entity<WIP_001_流程卡資料_機台編號Result>().HasNoKey();
        }
    }
}
