// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ERP.TESTModels.TESTEFModels;

public partial class WIP_001_生產回報_產出資料
{
    public int 產出編號 { get; set; }

    public int 回報編號 { get; set; }
    [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
    public DateTime 生產日期 { get; set; }

    public string 生產班別 { get; set; }

    public string 生產機台 { get; set; }

    public string 生產人員1 { get; set; }

    public string 生產人員2 { get; set; }

    public int Pass1 { get; set; }

    public int Pass2 { get; set; }

    public int Pass3 { get; set; }

    public int Pass4 { get; set; }

    public int 產出數量 { get; set; }

    public int 不良數量 { get; set; }

    public int? 抽樣數量 { get; set; }

    public string 金線編號 { get; set; }

    public DateTime 建檔日期 { get; set; }

    public DateTime? KEYIN_DATE { get; set; }

    public string HOST_NAME { get; set; }

    public string HOST_IP { get; set; }

    public string 年月 { get; set; }

    public string 年 { get; set; }

    public string 月 { get; set; }

    public string 日 { get; set; }

    public string 星期 { get; set; }

    public int? 週 { get; set; }

    public int? 季 { get; set; }
}