// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ERP.TESTModels.TESTEFModels
{
    public partial class WIP_001_流程卡資料_各站異常代號Result
    {
        public int 不良編號 { get; set; }
        public string 不良代號 { get; set; }
        public string 不良原因 { get; set; }
        public string 不良英文原因 { get; set; }
        public int? HW_Bin { get; set; }
    }
}
