// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace 南岩ERP.TESTModels.TESTEFModels
{
    public partial class WIP_001_流程卡資料_機台編號Result
    {
        public string 機台編號 { get; set; }
    }
}
