// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace 南岩ERP.TESTModels.TESTEFModels;

public partial class 現有人員查詢
{
    public string 員工代號 { get; set; }

    public string 姓名 { get; set; }

    public string 英文姓名 { get; set; }

    public string 部門代號 { get; set; }

    public string 部門名稱 { get; set; }

    public string 職級代號 { get; set; }

    public string 職稱 { get; set; }

    public string 直間接代號 { get; set; }

    public string 本外勞 { get; set; }

    public string 公司mail帳號 { get; set; }

    public decimal 月盈餘基點 { get; set; }

    public decimal? 目前年資 { get; set; }

    public decimal? 年初年資 { get; set; }

    public decimal? 年底年資 { get; set; }

    public int? 特休年資 { get; set; }

    public DateTime 報到日期 { get; set; }

    public DateTime? 離職日期 { get; set; }

    public string 年終獎金 { get; set; }

    public int? 年齡 { get; set; }

    public string 學歷代號 { get; set; }

    public string 學歷 { get; set; }

    public DateTime? 復職日期 { get; set; }

    public string 復薪年月 { get; set; }

    public string 兼任部門代號 { get; set; }

    public DateTime 出生日期 { get; set; }

    public DateTime? 留職停薪日期 { get; set; }

    public string 人員別 { get; set; }

    public decimal 職等 { get; set; }
}