// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace 南岩ERP.Models
{
    public partial class MA_005_供應商資料查詢Result
    {
        public string 產品類別代號 { get; set; }
        public string 供應商編號 { get; set; }
        public string 供應商簡稱 { get; set; }
        public string 供應商英文簡稱 { get; set; }
        public string 供應商全名 { get; set; }
        public string 供應商英文全名 { get; set; }
        public string 連絡人 { get; set; }
        public string EMAIL { get; set; }
        public string ISO_EMAIL { get; set; }
    }
}
