// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using 南岩ERP.Models;

namespace 南岩ERP.Models;

public partial class nanoerpEntities
{
    [DbFunction("MA_005_供應商資料查詢", "dbo")]
    public IQueryable<MA_005_供應商資料查詢Result> MA_005_供應商資料查詢()
    {
        return FromExpression(() => MA_005_供應商資料查詢());
    }

    [DbFunction("SYS_MENU_選單驗證", "dbo")]
    public IQueryable<SYS_MENU_選單驗證_Result> SYS_MENU_選單驗證(string MAN_ID, string PRO_TYPE)
    {
        return FromExpression(() => SYS_MENU_選單驗證(MAN_ID, PRO_TYPE));
    }

    [DbFunction("SYS_RP_角色驗證", "dbo")]
    public IQueryable<SYS_RP_角色驗證_Result> SYS_RP_角色驗證(string MAN_ID, string PRO_TYPE, string PRO_ID)
    {
        return FromExpression(() => SYS_RP_角色驗證(MAN_ID, PRO_TYPE, PRO_ID));
    }

    [DbFunction("SYS_USER_驗證", "dbo")]
    public static string SYS_USER_驗證(string MAN_ID, string MAN_PSWD)
    {
        throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
    }

    [DbFunction("SYS_USER_驗證查詢", "dbo")]
    public IQueryable<SYS_USER_驗證查詢_Result> SYS_USER_驗證查詢(string MAN_ID, string MAN_PSWD)
    {
        return FromExpression(() => SYS_USER_驗證查詢(MAN_ID, MAN_PSWD));
    }

    protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<MA_005_供應商資料查詢Result>().HasNoKey();
        modelBuilder.Entity<SYS_MENU_選單驗證_Result>().HasNoKey();
        modelBuilder.Entity<SYS_RP_角色驗證_Result>().HasNoKey();
        modelBuilder.Entity<SYS_USER_驗證查詢_Result>().HasNoKey();
    }
}
