// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace 南岩ERP.Models;

public partial class QA_018_物質調查記錄_附件
{
    public int 物質調查附件流水號 { get; set; }

    public int 物質調查流水號 { get; set; }

    public string 附件檔名 { get; set; }

    public DateTime 建檔日期 { get; set; }

    public DateTime? KEYIN_DATE { get; set; }

    public string MAN_ID { get; set; }

    public string HOST_NAME { get; set; }

    public string HOST_IP { get; set; }

    public virtual QA_018_物質調查記錄_主檔 物質調查流水號Navigation { get; set; }
}