// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace 南岩ERP.Models;

public partial class QA_018_物質調查記錄_主檔
{
    public int 物質調查流水號 { get; set; }

    public string 物質調查編號 { get; set; }

    public string 調查人員 { get; set; }

    [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
    public DateTime? 調查日期 { get; set; }
    public string 調查事項 { get; set; }
    public string 調查事項英文 { get; set; }
    public string 內文2 { get; set; }
    public string 內文2英文 { get; set; }
    public string 內文3 { get; set; }
    public string 內文3英文 { get; set; }

    [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
    public DateTime? 回覆期限 { get; set; }

    public string 結案 { get; set; }

    [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
    public DateTime? 結案日期 { get; set; }

    public string 寄送狀態 { get; set; }

    [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
    public DateTime? 寄送日期 { get; set; }

    public string 附件路徑 { get; set; }

    public string 附件名稱 { get; set; }
    public string 備註 { get; set; }
    [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm}", ApplyFormatInEditMode = true)]
    public DateTime? 建檔日期 { get; set; }

    [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
    public DateTime? KEYIN_DATE { get; set; }

    public string MAN_ID { get; set; }

    public string HOST_NAME { get; set; }

    public string HOST_IP { get; set; }

    public virtual ICollection<QA_018_物質調查記錄_明細> QA_018_物質調查記錄_明細 { get; set; } = new List<QA_018_物質調查記錄_明細>();

    public virtual ICollection<QA_018_物質調查記錄_附件> QA_018_物質調查記錄_附件 { get; set; } = new List<QA_018_物質調查記錄_附件>();
}