// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERP.Models;

public partial class QA_018_物質調查記錄_明細
{
    public int 物質調查明細流水號 { get; set; }

    public int 物質調查流水號 { get; set; }

    public string 供應商編號 { get; set; }

    public string ISO_EMAIL { get; set; }

    public DateTime? 回覆日期 { get; set; }

    public string 回覆狀態 { get; set; }

    public string 備註 { get; set; }

    public DateTime? 寄送日期 { get; set; }

    public DateTime 建檔日期 { get; set; }

    public DateTime? KEYIN_DATE { get; set; }

    public string MAN_ID { get; set; }

    public string HOST_NAME { get; set; }

    public string HOST_IP { get; set; }

    public virtual QA_018_物質調查記錄_主檔 物質調查流水號Navigation { get; set; }
}