// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using ERP.Models.WIPEFModels;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace ERP.Models.WIPEFModels
{
    public partial interface IWIPContextProcedures
    {
        Task<int> WIP_001_生產回報_記錄更新_DBAsync(int? 回報編號, string NO_WAFER, int? 片數, int? No_Die_量, string 結束回報, string 彈匣編號, string 彈匣編號2, string 彈匣編號3, string 彈匣編號4, string 彈匣編號5, string 彈匣編號6, string HOST_NAME, string HOST_IP, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> WIP_001_生產回報_產出資料_記錄刪除Async(int? 產出編號, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> WIP_001_生產回報_產出資料_記錄更新Async(int? 產出編號, DateTime? 生產日期, string 生產班別, string 生產機台, string 生產人員1, string 生產人員2, int? 產出數量, int? 不良數量, string HOST_NAME, string HOST_IP, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> WIP_001_生產回報_產出資料_記錄新增Async(int? 回報編號, DateTime? 生產日期, string 生產班別, string 生產機台, string 生產人員1, string 生產人員2, int? 產出數量, int? 不良數量, string HOST_NAME, string HOST_IP, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
