// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace 南岩ERP.Models.WIPEFModels;

public partial class WIP_001_生產回報資料來源
{
    public int 回報編號 { get; set; }

    public string 流程卡號 { get; set; }

    public short 回報序號 { get; set; }

    public string 生產站別 { get; set; }

    public string 客戶編號 { get; set; }

    public string 訂單編號 { get; set; }

    public string 工單編號 { get; set; }

    public int 投入量 { get; set; }

    public int 不良數 { get; set; }

    public int 產出量 { get; set; }

    public int? 待產量 { get; set; }

    public int Pass1 { get; set; }

    public int Pass2 { get; set; }

    public int Pass3 { get; set; }

    public int Pass4 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 良品率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 不良率 { get; set; }

    public int QC_TEST { get; set; }

    public int 累計不良數 { get; set; }

    public string 主要生產機台 { get; set; }

    public string NO_WAFER { get; set; }

    public string 結束回報 { get; set; }

    public DateTime? 投產日期 { get; set; }

    public DateTime? 產出日期 { get; set; }

    public string 已上傳 { get; set; }

    public string 停止生產 { get; set; }

    public string 異常處理方式 { get; set; }

    public DateTime? 排程日期 { get; set; }

    public string 排程生產機台 { get; set; }

    public int? UPH { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 預估生產時數 { get; set; }

    public int 併批投入量 { get; set; }

    public int? 本批投入量 { get; set; }

    public int? 本批產出量 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 本批良品率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 本批不良率 { get; set; }

    public int 原投入量 { get; set; }

    public int 原片數 { get; set; }

    public int 片數 { get; set; }

    public int 電鍍片數 { get; set; }

    public int? 可電鍍片數 { get; set; }

    public int No_Die_量 { get; set; }

    public int Die_Shortage_量 { get; set; }

    public int Die_Over_量 { get; set; }

    public DateTime? Die_建檔日期 { get; set; }

    public DateTime? Die_KEYIN_DATE { get; set; }

    public string Die_MAN_ID { get; set; }

    public string Die_HOST_NAME { get; set; }

    public string Die_HOST_IP { get; set; }

    public DateTime? X_rays_DATE { get; set; }

    public string X_rays_MAN_ID { get; set; }

    public string X_rays_HOST_NAME { get; set; }

    public string X_rays_HOST_IP { get; set; }

    public string 彈匣編號 { get; set; }

    public int? 上一站回報編號 { get; set; }

    public int? 下一站回報編號 { get; set; }

    public DateTime 建檔日期 { get; set; }

    public DateTime? KEYIN_DATE { get; set; }

    public string HOST_NAME { get; set; }

    public string HOST_IP { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 刀痕寬度 { get; set; }

    public string 流程卡類別 { get; set; }

    public int? 本批投入子批數 { get; set; }

    public int? 併批投入子批數 { get; set; }

    public string 彈匣編號2 { get; set; }

    public string 彈匣編號3 { get; set; }

    public string 彈匣編號4 { get; set; }

    public string 彈匣編號5 { get; set; }

    public string 彈匣編號6 { get; set; }

    public string 砲彈坑檢測結案 { get; set; }

    public DateTime? 砲彈坑結案日期 { get; set; }

    public string 砲彈坑生產機台 { get; set; }

    public string 生產備註 { get; set; }

    public string 異常狀況 { get; set; }

    public int? 首次TEST不良數 { get; set; }

    public int? 首次TEST產出量 { get; set; }

    public int? 首測主要不良編號 { get; set; }

    public string SX1300測試批號 { get; set; }

    public string Tester_ID { get; set; }

    public string Tester_ID_2 { get; set; }

    public string Tester_ID_3 { get; set; }

    public string Test_Software_Rev { get; set; }
    [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
    public DateTime? Time_Lot_Start { get; set; }
    [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
    public DateTime? Time_Lot_End { get; set; }

    public int? FunctionFailQty { get; set; }

    public int? ScrapQty { get; set; }

    public int? EQC數量 { get; set; }

    public string 抽樣方法 { get; set; }

    public int? 抽樣數量 { get; set; }

    public string 成品料號 { get; set; }

    public string 成品大類別 { get; set; }

    public string 成品小類別 { get; set; }

    public int? Wafer入庫數量 { get; set; }

    public int? Wafer產出數量 { get; set; }

    public decimal? 工單投入量 { get; set; }

    public int? DB產出量 { get; set; }

    public int? TF產出量 { get; set; }

    public int? DB未結案數 { get; set; }

    public int? TF未結案數 { get; set; }

    public decimal? Die_Shortage_Qty { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? Die_Shortage_Yield { get; set; }

    public decimal? Die_Over_Qty { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? Die_Over_Yield { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? Assembly_Yield { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 封裝不良率 { get; set; }

    public int? 各站累計不良數 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 各站Assembly_Yield { get; set; }

    public string 是否CP { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 訂單數量 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? Overall_Yield { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 標準封裝單站良率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 標準封裝良率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 標準測試單站良率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 標準測試Open_Short比率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 標準測試Vision_Lost比率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 標準測試Open_Short_Vision_Lost比率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 標準測試Lead比率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 標準測試Marking比率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 標準測試Vision比率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 標準測試Lost比率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 標準測試Function_Fail比率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 標準FVI_Vision比率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 標準Die_Shortage比率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 標準Die_Over比率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 標準Short比率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 標準CAP比率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 要求封裝良率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 要求單站良率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 要求Die_Shortage比率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 要求Die_Over比率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 要求Short比率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 要求CAP比率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 標準測試VF_Fail比率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 要求VF_Fail比率 { get; set; }

    public string 生產站別彙整 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 要求封裝Hold比率 { get; set; }

    public int? 流程卡DB產出量 { get; set; }

    public int? 流程卡TF產出量 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 流程卡Assy_Yield { get; set; }

    public short? Leadframe_Pad顆數 { get; set; }

    public string Mapping_File { get; set; }

    public int? DB待產量 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 單顆重量 { get; set; }

    public string 砲彈坑 { get; set; }

    public string 刻號 { get; set; }

    public int? 抽樣數量2 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 切割道寬度X { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 切割道寬度Y { get; set; }

    public int? 回報編號_2ND { get; set; }

    public int? 抽樣數量3 { get; set; }

    public int? 溢膠 { get; set; }

    public int? 總捲數 { get; set; }

    public int? EQC抽樣數量 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 要求良品率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 要求警告良品率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 要求Open_Short_比率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? Open_Short不良率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 要求Vision_Lost_比率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? Vision_Lost不良率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 要求Open_Short_Vision_Lost_比率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? Open_Short_Vision_Lost不良率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 要求Lead_比率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? Lead不良率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 要求Marking_比率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? Marking不良率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 要求Vision_比率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? Vision不良率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 要求Lost_比率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? Lost不良率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 要求Function_Fail_比率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? Function_Fail不良率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? Short不良率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? CAP不良率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? VF_Fail不良率 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 標準單顆重量 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? CURE總重量 { get; set; }

    public string 客供品異常單號 { get; set; }

    public string 客供品入庫編號 { get; set; }

    public string 切割刀具型號 { get; set; }
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:P3}")]
    public decimal? 刀痕寬度上限 { get; set; }
    [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
    public DateTime? 烘烤後可生產日期 { get; set; }

    public string 委託項目 { get; set; }

    public int? 取樣數量 { get; set; }
}