// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ERP.Models.WIPEFModels;

public partial class WIP_001_生產回報_不良品
{
    public int 回報編號 { get; set; }

    public int 不良編號 { get; set; }

    public int 不良數量 { get; set; }

    public byte? HW_Bin { get; set; }

    public DateTime? X_rays_DATE { get; set; }

    public string X_rays_MAN_ID { get; set; }

    public string X_rays_HOST_NAME { get; set; }

    public string X_rays_HOST_IP { get; set; }

    public int 不良品流水號 { get; set; }

    public DateTime 建檔日期 { get; set; }

    public DateTime? KEYIN_DATE { get; set; }

    public string HOST_NAME { get; set; }

    public string HOST_IP { get; set; }
}