// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace 南岩ERP.Models.WIPEFModels;

public partial class WIP_001_產線現有班別
{
    public string 生產班別 { get; set; }

    public string 中文說明 { get; set; }

    public string 英文說明 { get; set; }

    public string 班別歸屬 { get; set; }

    public string 產能班別 { get; set; }
}