// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ERP.Models.WIPEFModels
{
    public partial class WIP_001_生產回報_Cassette_NoResult
    {
        public string 工單編號 { get; set; }
        public string 流程卡號 { get; set; }
        public string Cassette_No { get; set; }
    }
}
