// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using 南岩ERP.Models.WIPEFModels;

namespace 南岩ERP.Models.WIPEFModels
{
    public partial class WIPContext
    {

        [DbFunction("WIP_001_生產回報_Cassette_No", "dbo")]
        public IQueryable<WIP_001_生產回報_Cassette_NoResult> WIP_001_生產回報_Cassette_No(string 工單編號)
        {
            return FromExpression(() => WIP_001_生產回報_Cassette_No(工單編號));
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<WIP_001_生產回報_Cassette_NoResult>().HasNoKey();
        }
    }
}
